name: Push rapidocr_web to pypi

on:
  push:
    branches: [ main ]
    paths:
      - 'ocrweb/rapidocr_web/**'
      - '!ocrweb/rapidocr_web/ocr_web.spec'
      - 'docs/doc_whl_rapidocr_web.md'
      - 'ocrweb/setup.py'
      - '.github/workflows/gen_whl_to_pypi_rapidocr_web.yml'

jobs:
  GenerateWHL_PushPyPi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Run setup.py
        run: |
          cd ocrweb
          pip install -r requirements.txt

          python -m pip install --upgrade pip
          python setup.py bdist_wheel "${{ github.event.head_commit.message }}"

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.RAPIDOCR_OPENVINO }}
          packages_dir: ocrweb/dist/
